plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '0.1.110'
    id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin' version '1.71.8'
    id 'me.modmuss50.mod-publish-plugin' version '0.7.3'
}

repositories {
    maven {
        // location of the maven that hosts Mantle and JEI files
        name = 'Progwml6 maven'
        url = 'https://dvs1.progwml6.com/files/maven'
    }
    maven { // TOP
        name 'McJty maven'
        url "https://maven.k-4u.nl"
    }
    flatDir {
        dirs 'libs'
    }
    maven {
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        // Patchouli && Provider
        name = "Blame Jared"
        url = "https://maven.blamejared.com"
    }
}

group = 'com.github.wendall911.magicalpsirevival'
version = "${minecraft_version}-${mod_version}"

java.toolchain.languageVersion = JavaLanguageVersion.of(java_version)

base {
    archivesName = "${mod_name}"
}

neoForge {
    version = neoforge_version
    parchment {
        minecraftVersion = parchment_mc_version
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            data()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    compileOnly "mezz.jei:jei-1.21.1-common-api:${jei_version}"
    implementation "mezz.jei:jei-1.21.1-neoforge:${jei_version}"

    runtimeOnly ("mcjty.theoneprobe:theoneprobe:1.21_neo-${probe_version}") {
        transitive = false
    }

    implementation "curse.maven:cyanide-541676:${cyanide_version}"
    runtimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}-NEOFORGE"
    //implementation "vazkii.psi:Psi:${psi_version}"

    implementation fileTree(dir: 'libs', include: '*.jar')
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

jar {
    manifest {
        attributes([
            "Specification-Title": mod_name,
            "Specification-Vendor": "${mod_author}",
            "Specification-Version": "${archiveVersion}",
            "Implementation-Title": "${mod_name}",
            "Implementation-Version": "${archiveVersion}",
            "Implementation-Vendor" :"${mod_author}",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}



processResources {
    def resourceTargets = ['META-INF/neoforge.mods.toml', 'pack.mcmeta', '*.mixins.json']
    def expandProps = [
        'version': version,
        'issue_tracker': issue_tracker,
        'license': license,
        'mod_id': mod_id,
        'display_name': display_name,
        'description': description,
        'display_url': display_url,
        'update_url': update_url,
        'authors': authors,
        'credits': credits,
        'logo_file': logo_file,
        'neoforge_mc_version_range': neoforge_mc_version_range,
        'neoforge_loader_version_range': neoforge_loader_version_range
    ]
    exclude '.cache'

    filesMatching(resourceTargets) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

def updates = tasks.register("generateUpdates", Copy) {
    it.outputs.upToDateWhen {
        false
    }

    it.from("./files/templates/") {
        include 'updates.json'
        expand 'version': version, 'minecraft_version': minecraft_version
    }

    it.into 'files/'
}

def changelogFile = project(":").projectDir.toString() + '/build/libs/' + project.getName() + '-' + version + '-changelog.txt'
def publishFile = project(":").projectDir.toString() + "/build/libs/${archivesBaseName}-${version}.jar"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.addAll(['neoforge'])

    if (project.hasProperty('mprcurseApiKey')) {
        curseforge {
            accessToken = project.mprcurseApiKey
            projectId = project.mprcurseId
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = true
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            requires('psi')
        }
    }
    if (project.hasProperty('mprModrinthId')) {
        modrinth {
            accessToken = project.modrinthKey
            projectId = project.mprModrinthId
            minecraftVersions.addAll("${release_versions}".split(','))
            requires('psi')
        }
    }
}

task changelog(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    file = new File(changelogFile);
    templateContent = file('files/templates/changelog.mustache').getText('UTF-8');
    fromRepo = file("$projectDir");
    toRef = "HEAD";
    fromRef = "${minecraft_version}-${last_mod_version}";
}

tasks.generateUpdates.mustRunAfter('jar')

tasks.build.dependsOn('changelog', 'generateUpdates')
