# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
mod_name=MagicalPsiRevival
modid=magipsi
mod_version=1.1.0.1
last_mod_version=1.0.0.1
java_version=17

# Common
minecraft_version=1.20.1
minecraft_short_version=1.20
minecraft_version_range=[1.20,1.20.2)
mixin_version=0.8.5

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2023.09.03

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=47.4.8
forge_version_range=[46,)
forge_mc_version_range=[1.20,1.20.2)

# Integration Mods
jei_version=15.20.0.112
probe_version=10.0.1-3
cyanide_version=5778405
patchouli_version=1.20.1-84.1
psi_version=1.20.1-105.547

# Mod options
mod_author=wendall911
issue_tracker=https://github.com/wendall911/MagicalPsiRevival/issues
license=MIT
display_name=Magical Psi Revival
description=Magical Psi Revival replaces every asset and description of Psi with a magic themed counterpart.
display_url=https://github.com/wendall911/MagicalPsiRevival
mod_update_branch=1.20.1
authors=wendall911
credits=Vazkill Wiiv TheIllusiveC4 Saiko-Chan
logo_file=logo.png

# CurseForge/Modrinth Options
release_type=release
release_versions=1.20.1
