# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=1.1.0.7
last_mod_version=1.1.0.5
group=com.github.wendall911.magipsi

# Common
minecraft_version=1.21.1
mixin_extras_version=0.3.5
mixin_version=0.8.5
# https://minecraft.wiki/w/Pack_format
pack_format=34
java_version=21

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2024.11.17

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.228
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21.1, 1.21.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.116.15+1.21.1
fabric_loader_version=0.19.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=["=1.21.1"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=11.0.4

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=19.27.0.340
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all
rei_version=16.0.799
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
architectury_version=13.0.8
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all
cloth_config_version=15.0.140
probe_version=12.0.4-6
cyanide_version=5782674
patchouli_version=1.21.1-92
# Until they actually push this up to maven, using the curse versions
psi_version=110
psi_neoforge_version=8786571
psi_fabric_version=8786570

# Mod options
mod_display_name=Magical Psi Revival
mod_id=magipsi
mod_name=MagicalPsiRevival
mod_author=wendall911
mod_credits=Vazkill Wiiv TheIllusiveC4 Saiko-Chan
license=MIT
mod_description=Magical Psi Revival replaces every asset and description of Psi with a magic themed counterpart.
mod_update_branch=1.21.1

# CurseForge/Modrinth Options
# Global properties are located in ~/.gradle/gradle.properties
# DO NOT put private keys here
curseforge_api_key_prop=mprcurseApiKey
curseforge_id=1320084
curseforge_slug=magical-psi-revival
modrinth_api_key_prop=modrinthKey
modrinth_id=DvvYZ4Cd
discord_webhook_prop=mprDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.21.1
