# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=1.1.0.4
last_mod_version=1.1.0.3

# Common
minecraft_version=1.21.1
mixin_version=0.8.5
# https://minecraft.wiki/w/Pack_format
pack_format=15
java_version=21

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2024.11.17

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.219
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21, 1.22)
neo_form_version=1.21.1-20240808.144430

# Integration and Testing Mods
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=19.22.1.316
probe_version=12.0.4-6
cyanide_version=5782674
patchouli_version=1.21.1-92
psi_version=107

# Mod options
mod_display_name=Magical Psi Revival
mod_id=magipsi
mod_name=MagicalPsiRevival
mod_author=wendall911
mod_credits=Vazkill Wiiv TheIllusiveC4 Saiko-Chan
license=MIT
mod_description=Magical Psi Revival replaces every asset and description of Psi with a magic themed counterpart.
mod_update_branch=1.21.1

# CurseForge/Modrinth Options
# Global properties are located in ~/.gradle/gradle.properties
# DO NOT put private keys here
curseforge_api_key_prop=mprcurseApiKey
curseforge_id=1320084
curseforge_slug=magical-psi-revival
modrinth_api_key_prop=modrinthKey
modrinth_id=DvvYZ4Cd
discord_webhook_prop=mprDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=1.21.1
