modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="${modid}"
    displayName="${display_name}"
    description="${description}"
    version="${version}"
    displayURL="${display_url}"
    updateJSONURL="https://raw.githubusercontent.com/wendall911/MagicalPsiRevival/${mod_update_branch}/files/updates.json"
    authors="${authors}"
    credits="${credits}"
    itemIcon="psi:psidust"
    logoFile="${logo_file}"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="psi"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
