modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
  modId="${mod_id}"
  displayName="${display_name}"
  description="${description}"
  version="${version}"
  displayURL="${display_url}"
  updateJSONURL="${update_url}"
  authors="${authors}"
  credits="${credits}"
  itemIcon="psi:psidust"
  logoFile="${logo_file}"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${neoforge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="psi"
    type="required"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
